version: 1.0
configuration:
  thirdEye:
    host: https://klingsten.visualstudio.com/
    organizationName: Klingsten
    backupPath: $ROAMING$\ThirdEye\backups
    workspaces: 
    - "*"
    teams: 
    - "*"     
    ignores:
      repositories:
      - "GlitchFinder"
      projects:
      - "*"
    nvd:
      url: https://services.nvd.nist.gov/rest/json/cves/2.0
      timeoutSeconds: 120
      pageSize: 2000
      delayIntervalSeconds: 2
      path: $ROAMING$\ThirdEye\nvd
      pathToUpdates: $ROAMING$\ThirdEye\nvd\updates
      latestCount: 100
  core:
    name: Third Eye
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    suggestions: 
    - exit
    roamingDirectory: ThirdEye
    modules:
      security:
        secrets:
        - name: CommandPrompt_encryptionManager
          options:
            target: User
        - name: TE_RepositoryToken
          options:
            target: User
        - name: TE_github_RepositoryToken
          options:
            target: User
        - name: TE_api_key
          options:
            target: User
      storage:
        applicationDataFolder: $ROAMING$\ThirdEye
        backupPath: backup
      ollama:
        baseAddress: localhost
        port: 11434
        model: gemma3:latest
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug